spring:
    profiles:
        active: dev
    application:
        name: Spring
    jpa:
        hibernate:
            dialect: org.hibernate.dialect.MySQL5Dialect
            ddl-auto: none
            show-sql: false
    liquibase:
        change-log: classpath:liquibase/master.xml

management:
    endpoints:
        web:
            exposure:
                include: '*'

com:
    app:
        jwtSecret: TheQuickBrownFoxJumpsOverTheLazyDog
        jwtExpiration: 1000