server: 
    port: 5000

spring:
    devtools:
        add-properties: false
    datasource:
        url: jdbc:mysql://chintan.cupfdasnp50r.us-east-1.rds.amazonaws.com/chintan?useSSL=false
        username: root
        password: remoteTiger
        driverClassName: com.mysql.cj.jdbc.Driver

logging:
    path: /tmp/logs
    file: ${logging.path}/debug.log