spring:
    datasource:
        url: jdbc:mysql://localhost:3306/employee_crud?useSSL=false
        username: traning
        password: traning
        driverClassName: com.mysql.cj.jdbc.Driver

com:
    app:
        jwtSecret: TheQuickBrownFoxJumpsOverTheLazyDog
        jwtExpiration: 1000
        